# Generated by Django 4.1.7 on 2023-10-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_cart_buyproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='delivery',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
