# Generated by Django 4.1.7 on 2023-10-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_buyproduct_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='delivery',
            field=models.CharField(max_length=50),
        ),
    ]
