# Generated by Django 4.1.7 on 2023-10-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_buyproduct_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
